### ISSUE TITLE
Library loader

### ISSUE THREAD

**Issue by Zolicha** [requery/sqlite-android#105]
On some devices there is a problem loading the native library since a wrong package installation.

I've solved this problem using the "[ReLinker](https://github.com/KeepSafe/ReLinker)" library which extract the native source code from the APK if not presented.

In my opinion there are 2 easy solutions for that.
1. Expose an API for custom native loading implementation.
2. Use "ReLinker" directly.

Currently I change the loading to be at the "SQLiteOpenHelper" instead of "SQLiteDatabase" since the ReLinker need the android context.
`ReLinker.loadLibrary(context, "sqlite3x");`

**Comment by M66B** [comment]
Since ReLinker can solve this likely rare Android problem, it is IMHO not a good idea to add an API for this.

**Comment by brianliyang** [comment]
I've been using ReLinker alongside Requery for over well over a year and this particular issue still appears in production. The issue is rare (affecting a small handful of users) but is persistent across several OS versions. I'm not sure how else to address the issue but I'd like to share a bit more information here for the record.

Here is the specific trace seen in production:

```
Caused by java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlite3x.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at io.requery.android.database.sqlite.SQLiteDatabase.<clinit>(SQLiteDatabase.java:91)
       at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:718)
       at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
       at io.requery.android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:199)
       ... my app stack traces ...
```

The issue is happening in fairly general places. I have database read operations when the app foregrounds and sometimes when the app is in the background.

I'm using ReLinker in the way described here already:

```
ReLinker.loadLibrary(context, "sqlite3x")
```

I agree with the aforementioned comment here that including ReLinker is probably not necessary as part of this library. I'm hoping others may be able to chime in on what might be going on here or at least share whether they are observing this issue in their apps out in the wild. I think I'm using Requery in fairly standard ways in my app so I'm surprised by the lack of more reports of this issue by others.

**Comment by brianliyang** [comment]
I've been using ReLinker alongside Requery for over well over a year and this particular issue still appears in production. The issue is rare (affecting a small handful of users) but is persistent across several OS versions. I'm not sure how else to address the issue but I'd like to share a bit more information here for the record.

Here is the specific trace seen in production:

```
Caused by java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlite3x.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at io.requery.android.database.sqlite.SQLiteDatabase.<clinit>(SQLiteDatabase.java:91)
       at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:718)
       at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
       at io.requery.android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:199)
       ... my app stack traces ...
```

The issue is happening in fairly general places. I have database read operations when the app foregrounds and sometimes when the app is in the background.

I'm using ReLinker in the way described here already:

```
ReLinker.loadLibrary(context, "sqlite3x")
```

I've also noticed a separate error being reported from ReLinker that occurs in tandem (from same device and almost the same frequency) that might give a little more detail to the issue. This particular trace came from a "Samsung S20 Ultra 5G" on Android 13.

```
Non-fatal Exception: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libsqlite3x.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       ... my app stack traces ...
```

I agree with the aforementioned comment here that including ReLinker is probably not necessary as part of this library. I'm hoping others may be able to chime in on what might be going on here or at least share whether they are observing this issue in their apps out in the wild. I think I'm using Requery in fairly standard ways in my app so I'm surprised by the lack of more reports of this issue by others.

**Comment by alenz316** [comment]
@brianliyang You are not alone!

We are also experiencing the same issues:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlite3x.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at io.requery.android.database.sqlite.SQLiteDatabase.<clinit>(SQLiteDatabase.java:91)
       at io.requery.android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java)
       ... our app stack trace initializing the DB ...
```
We also use ReLinker and get the same exception you do 
```
Non-fatal Exception: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libsqlite3x.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
      ... our app stack trace from our Application class ...
 ```

**Comment by d2callpod** [comment]
I get this error by side loading a bundle onto the wrong device. This is most likely caused by users trying to side load on the wrong device. I have reproduced it like this... 

1. Create a bundle (e.g. `./gradlew bundleDebug`)
2. Create device specific apks using the bundle tool (`bundletool build-apks --bundle app/build/outputs/bundle...`)
3. Install the bundle on the device the apks were created for (`bundletool install-apks --apks bundle.tmp/...`)
4. Get the path of the base APK from the device (`adb shell pm path com.example.app...`)
5. Pull the base apk from the device (`adb pull /data/data/.../base.apk`)
6. Install the `base.apk` onto a difference device (`adb install base.apk`)

The way I was solving this is by using the `MissingSplitsManager`. However that has now been deprecated for a while and is part of the Play Core library that is now End Of Life. The play store will not allow any apps using that library.

I don't have a solution yet.

**Comment by d2callpod** [comment]
Are you reproducing this locally or is it only crash reports in the store? I'm testing side loading of an incomplete apk (base.apk from a bundle apk) and I'm getting this error. I'm working on preventing this error and showing the user a warning instead of it crashing.

**Comment by brianliyang** [comment]
So far I'm only witnessing this issue in production crash reports, haven't been able to reproduce it locally.

**Comment by StainlessStlRat** [comment]
Just want to throw my vote in that I'm also experiencing this (with ReLinker) on a small handful of devices
