### ISSUE TITLE
proguard error

### ISSUE THREAD

**Issue by mahramane** [requery/sqlite-android#185]
Hi
When i use proguard for release application i get following error:
java version : 17
agp version: 8.1.1

```
----- class 'Lio/requery/android/database/sqlite/SQLiteConnection;' cl=0x141067f0 -----
                                                                                                      objectSize=396 (224 from super)
                                                                                                      access=0x8000.0011
                                                                                                      super='java.lang.Class<java.lang.Object>' (cl=0x0)
                                                                                                      interfaces (1):
                                                                                                         0: java.lang.Class<i0.f> (cl=0x141067f0)
                                                                                                      vtable (22 entries, 11 in super):
                                                                                                         0: void io.requery.android.database.sqlite.SQLiteConnection.close()
                                                                                                         1: void io.requery.android.database.sqlite.SQLiteConnection.collectDbStats(java.util.ArrayList)
                                                                                                         2: void io.requery.android.database.sqlite.SQLiteConnection.collectDbStatsUnsafe(java.util.ArrayList)
                                                                                                         3: java.lang.String io.requery.android.database.sqlite.SQLiteConnection.describeCurrentOperationUnsafe()
                                                                                                         4: void io.requery.android.database.sqlite.SQLiteConnection.dump(android.util.Printer, boolean)
                                                                                                         5: void io.requery.android.database.sqlite.SQLiteConnection.dumpUnsafe(android.util.Printer, boolean)
                                                                                                         6: void io.requery.android.database.sqlite.SQLiteConnection.enableLocalizedCollators()
                                                                                                         7: void io.requery.android.database.sqlite.SQLiteConnection.execute(java.lang.String, java.lang.Object[], i0.g)
                                                                                                         8: android.os.ParcelFileDescriptor io.requery.android.database.sqlite.SQLiteConnection.executeForBlobFileDescriptor(java.lang.String, java.lang.Object[], i0.g)
                                                                                                         9: int io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(java.lang.String, java.lang.Object[], i0.g)
                                                                                                        10: int io.requery.android.database.sqlite.SQLiteConnection.executeForCursorWindow(java.lang.String, java.lang.Object[], io.requery.android.database.CursorWindow, int, int, boolean, i0.g)
                                                                                                        11: long io.requery.android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(java.lang.String, java.lang.Object[], i0.g)
                                                                                                        12: long io.requery.android.database.sqlite.SQLiteConnection.executeForLong(java.lang.String, java.lang.Object[], i0.g)
                                                                                                        13: java.lang.String io.requery.android.database.sqlite.SQLiteConnection.executeForString(java.lang.String, java.lang.Object[], i0.g)
                                                                                                        14: void io.requery.android.database.sqlite.SQLiteConnection.finalize()
                                                                                                        15: boolean io.requery.android.database.sqlite.SQLiteConnection.isPreparedStatementInCache(java.lang.String)
                                                                                                        16: boolean io.requery.android.database.sqlite.SQLiteConnection.isPrimaryConnection()
                                                                                                        17: void io.requery.android.database.sqlite.SQLiteConnection.onCancel()
                                                                                                        18: void io.requery.android.database.sqlite.SQLiteConnection.prepare(java.lang.String, io.requery.android.database.sqlite.SQLiteStatementInfo)
                                                                                                        19: void io.requery.android.database.sqlite.SQLiteConnection.reconfigure(io.requery.android.database.sqlite.SQLiteDatabaseConfiguration)
                                                                                                        20: void io.requery.android.database.sqlite.SQLiteConnection.setOnlyAllowReadOnlyOperations(boolean)
                                                                                                        21: java.lang.String io.requery.android.database.sqlite.SQLiteConnection.toString()
                                                                                                      direct methods (60 entries):
                                                                                                         0: void io.requery.android.database.sqlite.SQLiteConnection.<clinit>()
                                                                                                         1: void io.requery.android.database.sqlite.SQLiteConnection.<init>(io.requery.android.database.sqlite.SQLiteConnectionPool, io.requery.android.database.sqlite.SQLiteDatabaseConfiguration, int, boolean)
                                                                                                         2: void io.requery.android.database.sqlite.SQLiteConnection.access$200(io.requery.android.database.sqlite.SQLiteConnection, io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement)
                                                                                                         3: java.lang.String io.requery.android.database.sqlite.SQLiteConnection.access$300(java.lang.String)
                                                                                                         4: byte[] io.requery.android.database.sqlite.SQLiteConnection.access$500()
                                                                                                         5: io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement io.requery.android.database.sqlite.SQLiteConnection.acquirePreparedStatement(java.lang.String)
                                                                                                         6: void io.requery.android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement)
                                                                                                         7: void io.requery.android.database.sqlite.SQLiteConnection.attachCancellationSignal(i0.g)
2023-09-09 16:34:12.570  9644-9644  om.ainoapp.aino         com.ainoapp.aino                     E       8: void io.requery.android.database.sqlite.SQLiteConnection.bindArguments(io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement, java.lang.Object[])
                                                                                                         9: java.lang.String io.requery.android.database.sqlite.SQLiteConnection.canonicalizeSyncMode(java.lang.String)
                                                                                                        10: void io.requery.android.database.sqlite.SQLiteConnection.detachCancellationSignal(i0.g)
                                                                                                        11: void io.requery.android.database.sqlite.SQLiteConnection.dispose(boolean)
                                                                                                        12: void io.requery.android.database.sqlite.SQLiteConnection.finalizePreparedStatement(io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement)
                                                                                                        13: io.requery.android.database.sqlite.SQLiteDebug$DbStats io.requery.android.database.sqlite.SQLiteConnection.getMainDbStatsUnsafe(int, long, long)
                                                                                                        14: int io.requery.android.database.sqlite.SQLiteConnection.getTypeOfObject(java.lang.Object)
                                                                                                        15: boolean io.requery.android.database.sqlite.SQLiteConnection.hasCodec()
                                                                                                        16: boolean io.requery.android.database.sqlite.SQLiteConnection.isCacheable(int)
                                                                                                        17: void io.requery.android.database.sqlite.SQLiteConnection.nativeBindBlob(long, long, int, byte[])
                                                                                                        18: void io.requery.android.database.sqlite.SQLiteConnection.nativeBindDouble(long, long, int, double)
                                                                                                        19: void io.requery.android.database.sqlite.SQLiteConnection.nativeBindLong(long, long, int, long)
                                                                                                        20: void io.requery.android.database.sqlite.SQLiteConnection.nativeBindNull(long, long, int)
                                                                                                        21: void io.requery.android.database.sqlite.SQLiteConnection.nativeBindString(long, long, int, java.lang.String)
                                                                                                        22: void io.requery.android.database.sqlite.SQLiteConnection.nativeCancel(long)
                                                                                                        23: void io.requery.android.database.sqlite.SQLiteConnection.nativeClose(long)
                                                                                                        24: void io.requery.android.database.sqlite.SQLiteConnection.nativeExecute(long, long)
                                                                                                        25: int io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForBlobFileDescriptor(long, long)
                                                                                                        26: int io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(long, long)
                                                                                                        27: long io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(long, long, long, int, int, boolean)
                                                                                                        28: long io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(long, long)
                                                                                                        29: long io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForLong(long, long)
                                                                                                        30: java.lang.String io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForString(long, long)
                                                                                                        31: void io.requery.android.database.sqlite.SQLiteConnection.nativeFinalizeStatement(long, long)
                                                                                                        32: int io.requery.android.database.sqlite.SQLiteConnection.nativeGetColumnCount(long, long)
                                                                                                        33: java.lang.String io.requery.android.database.sqlite.SQLiteConnection.nativeGetColumnName(long, long, int)
                                                                                                        34: int io.requery.android.database.sqlite.SQLiteConnection.nativeGetDbLookaside(long)
                                                                                                        35: int io.requery.android.database.sqlite.SQLiteConnection.nativeGetParameterCount(long, long)
                                                                                                        36: boolean io.requery.android.database.sqlite.SQLiteConnection.nativeHasCodec()
                                                                                                        37: boolean io.requery.android.database.sqlite.SQLiteConnection.nativeIsReadOnly(long, long)
                                                                                                        38: long io.requery.android.database.sqlite.SQLiteConnection.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean)
                                                                                                        39: long io.requery.android.database.sqlite.SQLiteConnection.nativePrepareStatement(long, java.lang.String)
                                                                                                        40: void io.requery.android.database.sqlite.SQLiteConnection.nativeRegisterCustomFunction(long, io.requery.android.database.sqlite.SQLiteCustomFunction)
                                                                                                        41: void io.requery.android.database.sqlite.SQLiteConnection.nativeRegisterFunction(long, io.requery.android.database.sqlite.SQLiteFunction)
                                                                                                        42: void io.requery.android.database.sqlite.SQLiteConnection.nativeRegisterLocalizedCollators(long, java.lang.String)
                                                                                                        43: void io.requery.android.database.sqlite.SQLiteConnection.nativeResetCancel(long, boolean)
2023-09-09 16:34:12.571  9644-9644  om.ainoapp.aino         com.ainoapp.aino                     E      44: void io.requery.android.database.sqlite.SQLiteConnection.nativeResetStatementAndClearBindings(long, long)
                                                                                                        45: io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement io.requery.android.database.sqlite.SQLiteConnection.obtainPreparedStatement(java.lang.String, long, int, int, boolean)
                                                                                                        46: io.requery.android.database.sqlite.SQLiteConnection io.requery.android.database.sqlite.SQLiteConnection.open(io.requery.android.database.sqlite.SQLiteConnectionPool, io.requery.android.database.sqlite.SQLiteDatabaseConfiguration, int, boolean)
                                                                                                        47: void io.requery.android.database.sqlite.SQLiteConnection.open()
                                                                                                        48: void io.requery.android.database.sqlite.SQLiteConnection.recyclePreparedStatement(io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement)
                                                                                                        49: void io.requery.android.database.sqlite.SQLiteConnection.releasePreparedStatement(io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement)
                                                                                                        50: void io.requery.android.database.sqlite.SQLiteConnection.setAutoCheckpointInterval()
                                                                                                        51: void io.requery.android.database.sqlite.SQLiteConnection.setForeignKeyModeFromConfiguration()
                                                                                                        52: void io.requery.android.database.sqlite.SQLiteConnection.setJournalMode(java.lang.String)
                                                                                                        53: void io.requery.android.database.sqlite.SQLiteConnection.setJournalSizeLimit()
                                                                                                        54: void io.requery.android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration()
                                                                                                        55: void io.requery.android.database.sqlite.SQLiteConnection.setPageSize()
                                                                                                        56: void io.requery.android.database.sqlite.SQLiteConnection.setSyncMode(java.lang.String)
                                                                                                        57: void io.requery.android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration()
                                                                                                        58: void io.requery.android.database.sqlite.SQLiteConnection.throwIfStatementForbidden(io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement)
                                                                                                        59: java.lang.String io.requery.android.database.sqlite.SQLiteConnection.trimSqlForDisplay(java.lang.String)
                                                                                                      static fields (3 entries):
                                                                                                         0: byte[] io.requery.android.database.sqlite.SQLiteConnection.EMPTY_BYTE_ARRAY
                                                                                                         1: java.lang.String[] io.requery.android.database.sqlite.SQLiteConnection.EMPTY_STRING_ARRAY
                                                                                                         2: java.util.regex.Pattern io.requery.android.database.sqlite.SQLiteConnection.TRIM_SQL_PATTERN
                                                                                                      instance fields (12 entries):
                                                                                                         0: int io.requery.android.database.sqlite.SQLiteConnection.mCancellationSignalAttachCount
                                                                                                         1: io.requery.android.database.sqlite.CloseGuard io.requery.android.database.sqlite.SQLiteConnection.mCloseGuard
                                                                                                         2: io.requery.android.database.sqlite.SQLiteDatabaseConfiguration io.requery.android.database.sqlite.SQLiteConnection.mConfiguration
                                                                                                         3: int io.requery.android.database.sqlite.SQLiteConnection.mConnectionId
                                                                                                         4: long io.requery.android.database.sqlite.SQLiteConnection.mConnectionPtr
                                                                                                         5: boolean io.requery.android.database.sqlite.SQLiteConnection.mIsPrimaryConnection
                                                                                                         6: boolean io.requery.android.database.sqlite.SQLiteConnection.mIsReadOnlyConnection
                                                                                                         7: boolean io.requery.android.database.sqlite.SQLiteConnection.mOnlyAllowReadOnlyOperations
                                                                                                         8: io.requery.android.database.sqlite.SQLiteConnectionPool io.requery.android.database.sqlite.SQLiteConnection.mPool
                                                                                                         9: io.requery.android.database.sqlite.SQLiteConnection$PreparedStatementCache io.requery.android.database.sqlite.SQLiteConnection.mPreparedStatementCache
                                                                                                        10: io.requery.android.database.sqlite.SQLiteConnection$PreparedStatement io.requery.android.database.sqlite.SQLiteConnection.mPreparedStatementPool
                                                                                                        11: io.requery.android.database.sqlite.SQLiteConnection$OperationLog io.requery.android.database.sqlite.SQLiteConnection.mRecentOperations
2023-09-09 16:34:12.572  9644-9644  om.ainoapp.aino         com.ainoapp.aino                     E  Failed to register native method io.requery.android.database.sqlite.SQLiteConnection.nativeLoadExtension(JLjava/lang/String;Ljava/lang/String;)V in /data/app/~~PARDIgJXAG1D1srcE8ghkg==/com.ainoapp.aino-iBFAjA-MYU8RGoHl31CVHw==/base.apk
2023-09-09 16:34:12.572  9644-9644  om.ainoapp.aino         com.ainoapp.aino                     A  jni_internal.cc:825] JNI FatalError called: RegisterNatives failed for 'io/requery/android/database/sqlite/SQLiteConnection'; aborting...
2023-09-09 16:34:12.774  9644-9644  om.ainoapp.aino         com.ainoapp.aino                     A  runtime.cc:676] Runtime aborting...
                                                                                                    runtime.cc:676] Dumping all threads without mutator lock held
                                                                                                    runtime.cc:676] All threads:
                                                                                                    runtime.cc:676] DALVIK THREADS (53):
                                                                                                    runtime.cc:676] "main" prio=10 tid=1 Runnable
                                                                                                    runtime.cc:676]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x7254b398 self=0x7a19e490d7b0
                                                                                                    runtime.cc:676]   | sysTid=9644 nice=-10 cgrp=top-app sched=0/0 handle=0x7a1b2bfda4f8
                                                                                                    runtime.cc:676]   | state=R schedstat=( 1135260538 475397809 1401 ) utm=49 stm=63 core=1 HZ=100
                                                                                                    runtime.cc:676]   | stack=0x7ffea2eb1000-0x7ffea2eb3000 stackSize=8188KB
                                                                                                    runtime.cc:676]   | held mutexes= "abort lock" "mutator lock"(shared held)
                                                                                                    runtime.cc:676]   native: #00 pc 000000000071ed04  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+132) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #01 pc 0000000000842dfe  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+334) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #02 pc 0000000000862cf8  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+1256) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #03 pc 000000000085bfad  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+493) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #04 pc 000000000085b1cf  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+2367) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #05 pc 000000000080551e  /apex/com.android.art/lib64/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+174) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #06 pc 00000000007ed875  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1381) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #07 pc 0000000000019cfc  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+60) (BuildId: 0aa332cd750579dec074c73abcd15956)
                                                                                                    runtime.cc:676]   native: #08 pc 000000000001924e  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+350) (BuildId: 0aa332cd750579dec074c73abcd15956)
                                                                                                    runtime.cc:676]   native: #09 pc 000000000060d2f9  /apex/com.android.art/lib64/libart.so (art::JNI<false>::FatalError(_JNIEnv*, char const*)+185) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #10 pc 0000000000023b24  /data/app/~~PARDIgJXAG1D1srcE8ghkg==/com.ainoapp.aino-iBFAjA-MYU8RGoHl31CVHw==/base.apk (offset 89e000) (jniRegisterNativeMethods+148) (BuildId: 34e856bf9902f0b998f505ac9cd5279c8826386c)
                                                                                                    runtime.cc:676]   native: #11 pc 000000000001fefb  /data/app/~~PARDIgJXAG1D1srcE8ghkg==/com.ainoapp.aino-iBFAjA-MYU8RGoHl31CVHw==/base.apk (offset 89e000) (JNI_OnLoad+59) (BuildId: 34e856bf9902f0b998f505ac9cd5279c8826386c)
                                                                                                    runtime.cc:676]   native: #12 pc 00000000005fe404  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+3748) (BuildId: 44bc52550248fc712a381bef164b75c7)
                                                                                                    runtime.cc:676]   native: #13 pc 0000000000005c60  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+384) (BuildId: 35ed32b49c4f94f82b61578dcca6e932)
                                                                                                    runtime.cc:676]   at java.lang.Runtime.nativeLoad(Native method)
                                                                                                    runtime.cc:676]   at java.lang.Runtime.nativeLoad(Runtime.java:1121)
                                                                                                    runtime.cc:676]   at java.lang.Runtime.loadLibrary0(Runtime.java:1075)

...
```

**Comment by mahramane** [comment]
?

**Comment by Helium314** [comment]
Alternatively you can add
`-keepclassmembers public class io.requery.android.database.sqlite.SQLiteConnection { *; }` to the proguard rules.
