### ISSUE TITLE
Support 16KB page size devices

### ISSUE THREAD

**Issue by mlewandowskipt** [requery/sqlite-android#195]
In Android 15 [support for 16KB page sizes has been announced](https://developer.android.com/about/versions/15/behavior-changes-all#16-kb).

However, `libsqlite3x.so` ELF segments are not aligned using 16 KB ELF alignment. This results in runtime crash when loading `libsqlite3x.so` on emulator that is configured to use 16KB page size:
```
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~-4biVEV5Nsst_51cMfx4Rg==/com.myapp-UApKSN3Ka7mJzUoGgCsMEg==/base.apk!/lib/arm64-v8a/libsqlite3x.so" (new hash type from the future?)
    at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
    at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
    at java.lang.System.loadLibrary(System.java:1765)
    at io.requery.android.database.sqlite.SQLiteDatabase.<clinit>(Unknown Source:2)
    at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(Unknown Source:95)
    at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SourceFile:3)
    at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SourceFile:1)
```

This can also be verified by preparing and running `alignment.sh` script [as described in the documentation](https://developer.android.com/guide/practices/page-sizes#test).

The solution is to compile `libsqlite3x.so` with 16KB ELF alignment as described [here](https://developer.android.com/guide/practices/page-sizes#compile-16-kb-alignment).

**Comment by adrian-niculescu** [comment]
https://github.com/requery/sqlite-android/pull/203 fixes this issue. I updated to [version 3.49.0](https://github.com/requery/sqlite-android/releases/tag/3.49.0) and was able to successfully run on a "16 KB Page Size" Android emulator. I believe this can be closed now. Thank you!

**Comment by tachubgame** [comment]
Having issues with this building in unity 2022.3.59f1 
ERROR:/Users/sssss/.gradle/caches/transforms-3/dd1aeef93cbddb7366f2db823c9ebd45/transformed/core-1.15.0-runtime.jar: D8: java.lang.NullPointerException

**Comment by hiSandog** [comment]
Since one comment reports 3.49.0 working on a 16 KB page-size emulator, it may be worth turning that into a release verification item before closing. A small CI or manual release checklist could run Android's alignment script against all packaged ABIs and then load `libsqlite3x.so` on a 16 KB emulator. That would also separate the original ELF alignment problem from the later Unity/D8 build issue, which sounds unrelated.
