### ISSUE TITLE
Could not open database

### ISSUE THREAD

**Issue by thelong1EU** [requery/sqlite-android#38]
I get this error from a couple of users. Do you know anything about this?
```
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
#################################################################
Error Code : 14 (SQLITE_CANTOPEN)
Caused By : Unable to open the database file.
	(unknown error (code 14): Could not open database)
#################################################################
       at io.requery.android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:223)
       at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
       at io.requery.android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:467)
       at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:188)
       at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:180)
       at io.requery.android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:827)
       at io.requery.android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:799)
       at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:674)
```

**Comment by npurushe** [comment]
Possibly the database was not closed previously before another application run, would need more information, this can happen in the Android OS SQLite wrapper as well.

**Comment by songliao-branch** [comment]
Possible solution here https://github.com/agrosner/DBFlow/issues/380
