### ISSUE TITLE
 A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by thelong1EU** [requery/sqlite-android#41]
I keep getting this error because I'm not closing the db. But I don't want to close and open it again and again. How can I stop this error from logs.

```
W/SQLite: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                          java.lang.Throwable: Explicit termination method 'close' not called
                                                              at io.requery.android.database.sqlite.CloseGuard.open(CloseGuard.java:188)
                                                              at io.requery.android.database.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:183)
                                                              at io.requery.android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:204)
                                                              at io.requery.android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:467)
                                                              at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:188)
                                                              at io.requery.android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:180)
                                                              at io.requery.android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:827)
                                                              at io.requery.android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:796)
                                                              at io.requery.android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:699)
                                                              at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:236)
                                                              at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:170)
```

**Comment by npurushe** [comment]
Yeah it is typical to not close the database explicitly in an android app, however this is just a warning message and the android os database api does the same thing iirc. If you are sure you are using the api correctly (e.g. just opening the database once in your app) then you can just ignore the message.

**Comment by thelong1EU** [comment]
Is there a way to stop it?

**Comment by thelong1EU** [comment]
Sorry, did see that. So do you know a way?

**Comment by npurushe** [comment]
setting `CloseGuard.setReporter` with a reporting callback function that does nothing is the only way, it suppressed all the CloseGuard messages
