### ISSUE TITLE
SupportSQLiteDatabase.setMaxSqlCacheSize(0) throws IllegalArgumentException

### ISSUE THREAD

**Issue by benasher44** [requery/sqlite-android#99]
Setting the `maxSqlCacheSize` to 0 is allowed according to the SupportSQLiteDatabase database [docs](https://developer.android.com/reference/androidx/sqlite/db/SupportSQLiteDatabase.html#setMaxSqlCacheSize(int)) and the bounds check [here](https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteDatabase.java#L2040). However, setting 0 crashes the PreparedStatementCache because its parent class does not allow 0 as a value:
```
java.lang.IllegalArgumentException: maxSize <= 0
        at androidx.collection.LruCache.<init>(LruCache.java:53)
        at io.requery.android.database.sqlite.SQLiteConnection$PreparedStatementCache.<init>(SQLiteConnection.java:1334)
```

**Comment by benasher44** [comment]
FWIW, Android has the same bug :/
